r_tech_app:
    resource: "@RTechAppBundle/Resources/config/routing.yml"
    prefix:   /

r_tech_user:
    resource: "@RTechUserBundle/Resources/config/routing.yml"
    prefix:   /user

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin