r_tech_app_homepage:
    path: /index
    defaults: { _controller: RTechAppBundle:Default:index }

r_tech_media:
    path: /add-media
    defaults: { _controller: RTechAppBundle:Media:addMedia }


r_tech_category:
    path: /category
    defaults: { _controller: RTechAppBundle:Category:index }