<?php

namespace RTech\AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function byCategorie($slug)
    {
        $qb = $this
            ->createQueryBuilder('c')
            ->innerJoin('c.medias', 'm')
            ->where('c.slug = :slug')
            ->addSelect('m')
            ->setParameters(array(
                'slug'=>$slug
            ))
        ;
        return $qb
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }
}
