
# SECURITY
fos_user_security_login:
    path: /login
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    path: /login/check
    defaults: { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    path: /logout
    defaults: { _controller: FOSUserBundle:Security:logout }


# REGISTRATION
fos_user_registration_register:
    path: /register
    defaults: { _controller: RTechUserBundle:Registration:register }

fos_user_registration_check_email:
    path: /register/e-mail
    defaults: { _controller: RTechUserBundle:Registration:checkEmail }

# PROFILE
fos_user_profile_show:
    path: /profile
    defaults: { _controller: RTechUserBundle:Profile:show }

rtech_user_profile_edit:
    path: /profile/edit
    defaults: { _controller: RTechUserBundle:Profile:edit }

# CONTACT
rtech_user_contact:
    path: /contact
    defaults: { _controller: RTechUserBundle:Contact:index }