services:
    app.form.registration:
        class: RTech\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.form.profile:
        class: RTech\UserBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: app_user_profile }
